package database

var (
	migrations [][]string = [][]string{
		[]string{
			`CREATE TABLE spellschools (
				id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	            name VARCHAR(128) NOT NULL,
	            description VARCHAR(512));`,
			`CREATE TABLE spelltypes (
				id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
				title VARCHAR(128) NOT NULL);`,
			`CREATE TABLE spells (
				id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	            name VARCHAR(128) NOT NULL,
	            description VARCHAR(512),
				schoolId INTEGER NOT NULL REFERENCES spellschools(id) ON DELETE SET NULL,
				typeId INTEGER NOT NULL REFERENCES spelltypes(id) ON DELETE SET NULL,
				cooldown DOUBLE PRECISION NOT NULL,
				casttime DOUBLE PRECISION NOT NULL,
				charges INTEGER NOT NULL DEFAULT 1);`},
		[]string{
			`CREATE TABLE knowledges (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY);`,
			`CREATE TABLE knowledgespells (
				knowledgeId INTEGER NOT NULL REFERENCES knowledges(id) ON DELETE CASCADE,
				spellId INTEGER NOT NULL REFERENCES spells(id) ON DELETE CASCADE);`,
			`CREATE TABLE knowledgerecipes (
				knowledgeId INTEGER NOT NULL REFERNCES knowledges(id) ON DELETE CASCADE,
				recipeId INTEGER NOT NULL REFERNCES recipes(id) ON DELETE CASCADE);`,
			`CREATE TABLE quests (
				id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
				name VARCHAR(128) NOT NULL,
				description VARCHAR(512) NOT NULL,
				goals text[] NOT NULL);`,
			`CREATE TABLE knowledgequests (
				knowledgeId INTEGER NOT NULL REFERENCES knowledges(id) ON DELETE CASCADE,
				questId INTEGER NOT NULL REFERENCES quests(id) ON DELETE CASCADE);`}}
)
