package tables

const (
	IdFieldName            string = "id"
	NameField              string = "name"
	NameFieldLength        int32  = 128
	DescriptionField       string = "description"
	DescriptionFieldLength int32  = 512
	BaseCreateEntityQuery  string = `CREATE TABLE %s (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	%s)`
	BaseCreateGameEntityQuery string = `CREATE TABLE %s (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(128) NOT NULL,
	description VARCHAR(512),
	%s)`
)

type EntityDataModel struct {
	Id int32
}

type GameEntityDataModel struct {
	EntityDataModel
	Name        string
	Description string
}
